# Generated by Django 4.1.2 on 2022-11-03 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empfaenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faecher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fachbezeichnung', models.CharField(choices=[('DEUTSCH', 'Deutsch'), ('ENGLISCH', 'Englisch'), ('FRANZOESISCH', 'Franzoesisch'), ('LATEIN', 'Latein'), ('RUSSISCH', 'Russisch'), ('SPANISCH', 'Spanisch'), ('MATHEMATIK', 'Mathematik'), ('INFORMATIK', 'Informatik'), ('NATURWISSENSCHAFTEN', 'Naturwissenschaften'), ('TECHNIK', 'Technik'), ('GESELLSCHAFTSWISSENSCHAFTEN', 'Gesellschaftswissenschaften'), ('MUSIK', 'Musik'), ('SPORT', 'Sport'), ('BIOLOGIE', 'Biologie'), ('GESCHICHTE', 'Geschichte'), ('PHYSIK', 'Physik'), ('CHEMIE', 'Chemie'), ('ERDKUNDE', 'Erdkunde')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nachhilfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('klasse_von', models.CharField(max_length=3, null=True)),
                ('klasse_bis', models.CharField(max_length=3, null=True)),
                ('fach_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.faecher')),
                ('person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Detail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('klasse', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_uhrzeit', models.DateTimeField(null=True)),
                ('nachhilfe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.nachhilfe')),
                ('person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
                ('empfaenger_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='start.empfaenger')),
                ('person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personen_Faecher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachhilfeflag', models.BooleanField(default=0)),
                ('fach_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.faecher')),
                ('person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
