# Generated by Django 4.1.2 on 2022-11-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_alter_faecher_fachbezeichnung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faecher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
