# Generated by Django 4.1.2 on 2022-11-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_alter_nachhilfe_klasse_bis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachhilfe',
            name='klasse_bis',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nachhilfe',
            name='klasse_von',
            field=models.IntegerField(null=True),
        ),
    ]
