# Generated by Django 4.1.2 on 2022-11-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_alter_nachhilfe_klasse_bis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='empfaenger_ID',
            field=models.IntegerField(),
        ),
    ]
