# Generated by Django 4.1.2 on 2022-11-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_alter_sender_empfaenger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='newmessageflag',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='faecher',
            name='fachbezeichnung',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Empfaenger',
        ),
    ]
