# Generated by Django 4.1.2 on 2022-11-24 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('start', '0009_sender_newmessageflag_alter_faecher_fachbezeichnung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='empfaenger_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empfaenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sender',
            name='person_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
