# Generated by Django 4.1.2 on 2023-01-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0011_settings_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_content',
            name='datenschutz',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='settings_content',
            name='impressum',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
